services:
    asf_layout.twig.label:
        class: ASF\LayoutBundle\Twig\LabelExtension
        tags:
            - { name: "twig.extension" }
            
    asf_layout.twig.badge:
        class: ASF\LayoutBundle\Twig\BadgeExtension
        tags:
            - { name: "twig.extension" }
                    
    asf_layout.twig.icon:
        class: ASF\LayoutBundle\Twig\IconExtension
        arguments: ["%asf_layout.assets.twbs.icon_prefix%", "%asf_layout.assets.twbs.icon_tag%"]
        tags:
            - { name: "twig.extension" }
